export const GET_SUPERMARKETS = 'GET_SUPERMARKETS';
export const ADD_SUPERMARKET = 'ADD_SUPERMARKET';
export const DELETE_SUPERMARKET = 'DELETE_SUPERMARKET';
export const ADD_ITEMTOSHOP = 'ADD_ITEMTOSHOP';
export const ADD_ITEMTOBASKET = "ADD_ITEMTOBASKET"
export const DELETE_ITEMFROMBASKET = "DELETE_ITEMFROMBASKET"
export const DELETE_ALLFROMBASKET = "DELETE_ALLFROMBASKET"